server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://127.0.0.1:9411   # zipkin地址
    sleuth:
      sampler:
        probability: 1   # 采样率值，介于0-1之间，1表示全部采集

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
  #所有model所在包

#eureka-client相关
eureka:
  client:
    #    表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    #    是否从EurekaServer 抓取已经有的注册信息，默认为true，单节点无所谓，机器必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 单机版
      #      defaultZone: http://localhost:7001/eureka
      # 集群版,调用两个，7001与7002
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002:7002/eureka
  instance:
    instance-id: payment8001
    #    访问路径可以显示IP地址
    prefer-ip-address: true
    #    Eureka客户端向服务器端发送心跳的时间间隔，单位为秒（默认30s）
#    lease-renewal-interval-in-seconds: 30
    #    Eureka 服务端在收到最后一次心跳后等待时间上限，单位为s（默认90s），超时将会剔除服务
#    lease-expiration-duration-in-seconds: 20
