server:
  port: 8006
spring:
  application:
    name: cloud-payment-service8006
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  thymeleaf:
    cache: false
  #  consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        health-check-url: http://localhost:8006/actuator/health
#        heartbeat:
#          enabled: true
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
  #所有model所在包

