server:
  port: 9004
spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # nacos单机地址
management:
  endpoints:
    web:
      exposure:
        include: "*"
